### ISSUE TITLE
1.18.1 The game crashes on startup

### ISSUE THREAD

**Issue by Dr-WeiAL** [Fourmisain/SimpleDrawers#1]
[crash-2022-02-28_20.17.39-client.txt](https://github.com/Fourmisain/SimpleDrawers/files/8153235/crash-2022-02-28_20.17.39-client.txt)
I checked and fabric is up to date

**Comment by Dr-WeiAL** [comment]
I checked and the 1.18.2 version works, but the 1.18.1 version doesn't

**Comment by Dr-WeiAL** [comment]
Okay, I found out, it and create together will cause the game to start in a dead loop
@Fourmisain

**Comment by Fourmisain** [comment]
Yeah, that looks like the same issue as with Botania, something inside `ModelMerger.onPostBake`.

Aaand I think I fixed it!
The issue was that SimpleDrawers tried to handle models with `border_type` that don't belong to it (in this case to Botania and Create), which would cause the crash.

I published two new versions for 1.18 and 1.18.2, lemme know if there's still an issue with them!

**Comment by Dr-WeiAL** [comment]
![image](https://user-images.githubusercontent.com/47446553/156304928-5cb6aea5-416f-48bd-9ee1-056f0edf9ec8.png)
It can run normally, but there are some problems with the compatibility of the drawer and wthit?
[waila_errors.log](https://github.com/Fourmisain/SimpleDrawers/files/8167003/waila_errors.log)

**Comment by Fourmisain** [comment]
With the 1.18.2 update I updated the WTHIT integration as well so everything should work there.

The 1.18(.1) version still works with WTHIT version 4.4.1 and it looks like the API changed with version 4.5.0, so you can just use the older one for now (and hope no other mods breaks with it).

**Comment by Dr-WeiAL** [comment]
![image](https://user-images.githubusercontent.com/47446553/156351212-16d07deb-d608-43e2-8373-6413f27ded41.png)
I tried to put DrawerComponentProvider.java of 1.18.2 into the source code of 1.18, it seems to solve part of the problem
Then I set the drawer into the megane blacklist, and now it displays normally 
![image](https://user-images.githubusercontent.com/47446553/156352821-2ae4ec99-87ed-40bd-a2f5-bd288e30923f.png)
![image](https://user-images.githubusercontent.com/47446553/156352846-2e5e4437-3d12-4c4b-8617-95788db85246.png)
But the controller doesn't seem to display properly
![image](https://user-images.githubusercontent.com/47446553/156353249-29a83843-91b6-41e6-82f1-5cc3e50771ae.png)

**Comment by Fourmisain** [comment]
Ah, it's been a while since I looked at that controller, I think it was implemented pretty weirdly compared to Storage Drawers.
I'm pretty sure the controller has no support for WTHIT, so you are probably looking at megane output. So that should answer that mystery.

The controller itself might also not work as you expect since I believe it doesn't properly connect all the drawers but only checks a 3x3 area behind it, _I think_.
That was one of the things I was planning on rewriting eventually, but I'm still not feeling like actually working on the mod since I haven't even got a response from the original author and I don't really want to take it over without their consent (even though the license allows it).

**Comment by Dr-WeiAL** [comment]
The controller setting of this mod seems to be that it can only connect to the rear 3x3 drawer

> Drawer Controller: The Drawer Controller can be used to control a 3x3 area of drawers. The drawer controller has to face into the opposite direction of the 3x3 area to be able to accept or dispense items.

The original author has not updated for almost two years, it seems that he has given up on this mod, and his other mods have not been updated. Do you still have to wait for his reply?

**Comment by Fourmisain** [comment]
Well it's not _just_ that I'm waiting for a response but I'm recently not really into Minecraft modding or Minecraft in general.
I haven't played the game for a quite while and am basically in pure maintenance mode since December.

This will likely change once I can play the game with friends again, maybe find some cool new modpack, to get things going again, you know.
I've got a ton of modding stuff I've yet to finish, some impossibly large ideas too but those have to wait till I feel it again.
Minecraft is a game you can always come back to and motivation for it comes and goes, that's been true since I've played it in Beta (I think it was Beta).

Thanks for the input though!
I haven't actually realized the mod wasn't updated for so long, so once I get back into the groove, I might create a proper (rebranded) fork, but yeah, that's something for future me.

**Comment by Dr-WeiAL** [comment]
Well, my English is very poor, I used machine translation for all the front, and some words can't be conveyed in the translated language, which may be a little strange, so I feel that I can't help you on this point, I wish you a happy life!
